# Documentation: https://static-web-server.net/
# Docker Compose version used
version: "3.9"

# Defines the services that will be run
services:
    # Service name
    sws:
        # Docker image that will be used to create the container
        image: joseluisq/static-web-server:latest
        # Name assigned to the container that will be created
        container_name: sws
        # Container restart policy. "always" means the container will be restarted whenever it stops.
        restart: always
        
        # Environment variables passed to the container
        #environment:
        # Note: these environment variables are customizable, but also optional.
            #- SERVER_HOST=127.0.0.1 # IP address the server will listen to
            #- SERVER_PORT=80 # Port the server will listen to
            #- SERVER_ROOT=/public # Root directory where the server will serve the files
            
            ## To use an "Index of", the 3 parameters below must be uncommented
            #- SERVER_DIRECTORY_LISTING=true # Whether the server should list directories or not. If set to 'true', the server will list the contents of directories. If set to 'false', it will not.
            #- SERVER_DIRECTORY_LISTING_ORDER=6 # Specifies the order in which directory entries are listed. Acceptable values are 0 (Name asc), 1 (Name desc), 2 (Last modified asc), 3 (Last modified desc), 4 (Size asc), 5 (Size desc), 6 (Unordered).
            #- SERVER_DIRECTORY_LISTING_FORMAT=html # Specifies the output format for directory listings. Can be either 'html' (default) or 'json'. This setting is dependent on SERVER_DIRECTORY_LISTING being enabled.

        
        # Volumes mounted on the container. ${HOME}/Docker/SWS/html on the host will be mounted as /public in the container.
        volumes:
            - ${HOME}/Docker/SWS/html:/public
        
        # Labels assigned to the container. These are used by Traefik for HTTP routing.
        #labels:
        #  - "traefik.enable=true"
        #  - "traefik.frontend.entryPoints=https"
        #  - "traefik.backend=localhost_dev"
        #  - "traefik.frontend.rule=Host:localhost.dev"
        #  - "traefik.port=80"
        
        # Ports that will be exposed by the container. Port 8182 on the host will be directed to port 80 on the container.
        ports:
            - "8182:80"
        deploy:
            resources:
                limits:
                    # Limits the CPU usage by the container to 1 cores.
                    cpus: '1'
                    # Limits the memory usage by the container to 1GB.
                    memory: 1G
        healthcheck:
            # Checks the health of the container using curl to access port 8200.
            test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
            # The interval between each health check.
            interval: 30s
            # The maximum amount of time a health check can take before it is considered a failure.
            timeout: 10s
            # The number of consecutive health check failures required for the container to be considered unhealthy.
            retries: 6
        # Network the container will be connected to.
        networks:
            big-net:

# Defines the networks that will be created
networks:
    # Network name
    big-net:
        # Name assigned to the network
        name: big-net
